/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WorkEntry = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'entryType' : IDL.Text,
  'projectName' : IDL.Text,
  'date' : IDL.Text,
  'earnings' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'timeWorked' : IDL.Text,
});
export const PaginatedResult = IDL.Record({
  'totalEntries' : IDL.Nat,
  'page' : IDL.Nat,
  'entries' : IDL.Vec(WorkEntry),
  'totalPages' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWorkEntry' : IDL.Func([WorkEntry], [WorkEntry], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntriesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getEntryById' : IDL.Func([IDL.Nat], [IDL.Opt(WorkEntry)], ['query']),
  'getPaginatedEntries' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PaginatedResult],
      ['query'],
    ),
  'getTodayEarnings' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getTotalEarnings' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalWithdrawn' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchEntriesByProjectName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkEntry)],
      ['query'],
    ),
  'seedEntriesOnce' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WorkEntry = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'entryType' : IDL.Text,
    'projectName' : IDL.Text,
    'date' : IDL.Text,
    'earnings' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'timeWorked' : IDL.Text,
  });
  const PaginatedResult = IDL.Record({
    'totalEntries' : IDL.Nat,
    'page' : IDL.Nat,
    'entries' : IDL.Vec(WorkEntry),
    'totalPages' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWorkEntry' : IDL.Func([WorkEntry], [WorkEntry], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntriesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getEntryById' : IDL.Func([IDL.Nat], [IDL.Opt(WorkEntry)], ['query']),
    'getPaginatedEntries' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PaginatedResult],
        ['query'],
      ),
    'getTodayEarnings' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getTotalEarnings' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalWithdrawn' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchEntriesByProjectName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkEntry)],
        ['query'],
      ),
    'seedEntriesOnce' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };